# Limpieza del dataset de bienes raíces

Este es un conjunto de datos (dataset) reales que fue descargado usando técnicas de web scraping. El archivo contiene registros de **Fotocasa**, el cual es uno de los sitios más populares de bienes raíces en España. Contiene miles de datos de casas reales publicadas en la web www.fotocasa.com.

El dataset fue descargado hace algunos años y en ningún caso se obtuvo beneficio económico de ello.

Tu objetivo es extraer tanta información como sea posible con el conocimiento que tienes hasta ahora de ciencia de datos.

In [4]:
import pandas as pd

#### Ejercicio 00

Lee el dataset data/real_estate.csv e intenta visualizar la tabla (★☆☆)

In [6]:
# Este archivo CSV contiene puntos y comas en lugar de comas como separadores
df = pd.read_csv('../data/real_estate.csv', sep=';')
df

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

## Trabajando con un DataFrame

#### Ejercicio 01

¿Cuál es la casa más cara del dataset? (★☆☆)

Imprime la dirección y el precio de la casa seleccionada. Para visualizar el resultado utiliza un f-string. Por ejemplo:

```py
f'La casa más cara se encuentra en la dirección: {address} y su precio es {price} €'
```

In [7]:
max_price_house = df.loc[df['price'].idxmax()]

address = max_price_house['address']
price = max_price_house['price']

print(f'La casa más cara se encuentra en la dirección: {address} y su precio es {price} €')

La casa más cara se encuentra en la dirección: El Escorial y su precio es 8500000 €

#### Ejercicio 02

¿Cuál es la casa más barata del dataset? (★☆☆)

Imprime la dirección y el precio de la casa seleccionada utilizando f-string

In [8]:
min_price_house = df.loc[df['price'].idxmin()]

address = min_price_house['address']
price = min_price_house['price']

print(f'La casa más barata se encuentra en la dirección: {address} y su precio es {price} €')

La casa más barata se encuentra en la dirección: Parla y su precio es 0 €

#### Ejercicio 03

¿Cuál es la casa más grande del dataset? (★☆☆)

Imprime la dirección y el área de las casas seleccionadas utilizando f-string

In [9]:
max_surface_house = df.loc[df['surface'].idxmax()]

address = max_surface_house['address']
surface = max_surface_house['surface']

print(f'La casa más grande se encuentra en la dirección: {address} y su área es {surface} m²')

La casa más grande se encuentra en la dirección: Sevilla la Nueva y su área es 249000.0 m²

#### Ejercicio 04

¿Cuál es la casa más pequeña del dataset? (★☆☆)

In [10]:
min_surface_house = df.loc[df['surface'].idxmin()]

address = min_surface_house['address']
surface = min_surface_house['surface']

print(f'La casa más pequeña se encuentra en la dirección: {address} y su área es {surface} m²')

La casa más pequeña se encuentra en la dirección: Calle Amparo,  Madrid Capital y su área es 15.0 m²

#### Ejercicio 05.

¿El dataset contiene valores no admitidos (NAs)? (★☆☆)

- Muestra el nombre de las filas seguidas por un booleano (`True` o `False`) según contengan o no contengan NAs.
- También muestra el nombre de las columnas seguidas por un booleano (`True` o `False`) según contengan o no contengan NAs.

In [11]:
# Filas
rows_has_na = df.isna().any(axis=1)
print("--- NAs por Fila ---")
print(rows_has_na)

# Columnas
cols_has_na = df.isna().any(axis=0)
print("\n--- NAs por Columna ---")
print(cols_has_na)

--- NAs por Fila ---
0        True
1        True
2        True
3        True
4        True
         ...
15330    True
15331    True
15332    True
15333    True
15334    True
Length: 15335, dtype: bool

--- NAs por Columna ---
Unnamed: 0          False
id_realEstates      False
isNew               False
realEstate_name      True
phone_realEstate     True
url_inmueble        False
rooms                True
bathrooms            True
surface              True
price               False
date                False
description          True
address             False
country             False
level1              False
level2              False
level3              False
level4               True
level5              False
level6               True
level7               True
level8               True
upperLevel          False
countryId           False
level1Id            False
level2Id            False
level3Id            False
level4Id            False
level5Id            False
level6Id            False
level7Id            False
level8Id            False
accuracy            False
latitude            False
longitude           False
zipCode              True
customZone           True
dtype: bool

#### Ejercicio 06.

Elimina los NAs del dataset, si aplica (★★☆)

Muestra las dimensiones del DataFrame original y del DataFrame después de las eliminaciones.

In [12]:
# Elimina filas que tengan valores nulos solo en las columnas clave
df_clean = df.dropna(subset=['price', 'surface', 'address'])

print(f'Dimensiones del DataFrame original: {df.shape}')
print(f'Dimensiones del DataFrame sin NAs clave: {df_clean.shape}')

df = df.dropna(subset=['price', 'surface', 'address'])

Dimensiones del DataFrame original: (15335, 37)
Dimensiones del DataFrame sin NAs clave: (14085, 37)

#### Ejercicio 07

¿Cuantas poblaciones (columna level5) contiene el dataset? (★☆☆)

- Muestra una lista con los nombres de las poblaciones
- Muestra el total de las mismas

In [13]:
poblaciones = df['level5'].unique()

# Mostrar la lista de poblaciones
print("Lista de poblaciones:")
print(poblaciones)

# Mostrar el total de poblaciones únicas
total_poblaciones = df['level5'].nunique()
print(f"\nTotal de poblaciones únicas: {total_poblaciones}")

Lista de poblaciones:
<StringArray>
[        'Arganda del Rey',      'Boadilla del Monte',
             'Fuenlabrada',     'Las Rozas de Madrid',
         ' Madrid Capital',    'Villaviciosa de Odón',
                   'Pinto',               'Valdemoro',
            'Navalcarnero',      'Pozuelo de Alarcón',
 ...
   'Villavieja del Lozoya',                'Canencia',
 'Cabanillas de la Sierra',     'Buitrago del Lozoya',
        'Fresno de Torote',              'Robregordo',
       'Pinilla del Valle',               'Rascafría',
              'La Hiruela',    'Montejo de la Sierra']
Length: 168, dtype: str

Total de poblaciones únicas: 168

#### Ejercicio 08

¿Cuál es la media de precios en la población (columna level5) de "Arroyomolinos (Madrid)"? (★★☆)

In [14]:
media_arroyomolinos = df[df['level5'] == "Arroyomolinos (Madrid)"]['price'].mean()

print(f"La media de precios en Arroyomolinos (Madrid) es: {media_arroyomolinos:.2f} €")

La media de precios en Arroyomolinos (Madrid) es: 297351.23 €

#### Ejercicio 09.

¿Los precios promedios de "Valdemorillo" y "Galapagar" son iguales? (★★☆)

- Muestra ambos promedios
- Escribe en una celda markdown una conclusión sobre ellos

In [15]:
# Calcular ambos promedios
mean_valdemorillo = df[df['level5'] == "Valdemorillo"]['price'].mean()
mean_galapagar = df[df['level5'] == "Galapagar"]['price'].mean()

# Mostrar ambos promedios
print(f"Precio promedio en Valdemorillo: {mean_valdemorillo:.2f} €")
print(f"Precio promedio en Galapagar: {mean_galapagar:.2f} €")

Precio promedio en Valdemorillo: 371583.02 €
Precio promedio en Galapagar: 372108.65 €

### Conclusión

Al comparar las medias de precio entre ambas poblaciones, se observa que los precios promedios de Valdemorillo y Galapagar no son iguales, existe una diferencia en el valor medio de sus inmuebles de 525.63 €

#### Ejercicio 10

¿Los promedios de precio por metro cuadrado (precio/m2) de "Valdemorillo" y "Galapagar" son iguales? (★★☆)

> Pista: Crea una nueva columna llamada `pps` (*price per square* o precio por metro cuadrado) y luego analiza los valores.

- Muestra ambos promedios de precio por metro cuadrado
- Escribe en una celda markdown una conclusión sobre ellos

In [16]:
# Crear la nueva columna pps
df['pps'] = df['price'] / df['surface']

# Calcular los promedios
pps_valdemorillo = df[df['level5'] == "Valdemorillo"]['pps'].mean()
pps_galapagar = df[df['level5'] == "Galapagar"]['pps'].mean()

# Mostrar ambos promedios
print(f"Precio por m² promedio en Valdemorillo: {pps_valdemorillo:.2f} €/m²")
print(f"Precio por m² promedio en Galapagar: {pps_galapagar:.2f} €/m²")

Precio por m² promedio en Valdemorillo: 1317.95 €/m²
Precio por m² promedio en Galapagar: 1606.32 €/m²

### Conclusión

Al analizar el precio medio por metro cuadrado, se observa que los promedios de Valdemorillo y Galapagar tampoco son iguales, con una diferencia de 288.37 €/m² mas en Galapagar

#### Ejercicio 11

¿Cuántas agencia de bienes raíces contiene el dataset? (★★☆)

- Muestra el valor obtenido.

In [18]:
total_agencias = df['realEstate_name'].nunique()

print(f"El dataset contiene {total_agencias} agencias de bienes raíces.")

El dataset contiene 1711 agencias de bienes raíces.

#### Ejercicio 12

¿Cuál es la población (columna level5) que contiene la mayor cantidad de casas?(★★☆)

- Muestra la población y el número de casas.

In [19]:
top_poblacion = df['level5'].value_counts().idxmax()
num_casas = df['level5'].value_counts().max()

print(f"La población con la mayor cantidad de casas es '{top_poblacion}' con un total de {num_casas} propiedades.")

La población con la mayor cantidad de casas es ' Madrid Capital' con un total de 6237 propiedades.

---

## Trabajando con un subconjunto del DataFrame

#### Ejercicio 13

Ahora vamos a trabajar con el "cinturón sur" de Madrid.

Haz un subconjunto del DataFrame original que contenga las siguientes poblaciones (columna level5): "Fuenlabrada", "Leganés", "Getafe", "Alcorcón" (★★☆)

> Pista: Filtra el DataFrame original usando la columna `level5` y la función `isin`.

In [20]:
poblaciones_sur = ["Fuenlabrada", "Leganés", "Getafe", "Alcorcón"]

df_sur = df[df['level5'].isin(poblaciones_sur)]

df_sur.head()

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone,pps
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN,1034.883721
85,86,153152077,False,sinergical inmobiliaria,NaN,https://www.fotocasa.es/es/comprar/vivienda/le...,1.0,1.0,50.0,107000,...,0,0,0,0,1,"40,35059","-3,82693",NaN,NaN,2140.000000
94,95,153995577,False,viviendas365com,911226014.0,https://www.fotocasa.es/es/comprar/vivienda/le...,3.0,2.0,120.0,320000,...,0,0,0,0,0,"40,31933","-3,77574",NaN,NaN,2666.666667
109,110,153586414,False,area uno asesores inmobiliarios,912664081.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,3.0,142.0,425000,...,0,0,0,0,0,"40,3313411","-3,8313868",NaN,NaN,2992.957746
161,162,153440116,False,prolucisa,916350416.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,123.0,239500,...,0,0,0,0,0,"40,2744807718156","-3,79192471504211",NaN,NaN,1947.154472

#### Ejercicio 14

Calcula la media y la varianza de muestra para las siguientes variables: precio, habitaciones, superficie y baños (★★★)

> Debes usar el subset obtenido en la pregunta 13

- Crea y visualiza un diccionario con todos los valores

In [22]:
# Variables a analizar
columnas = ['price', 'rooms', 'surface', 'bathrooms']

estadisticas_sur = {}

for col in columnas:
    estadisticas_sur[f'{col}_media'] = df_sur[col].mean()
    estadisticas_sur[f'{col}_varianza'] = df_sur[col].var()

estadisticas_sur

{'price_media': np.float64(222009.1156289708),
 'price_varianza': np.float64(15166379956.903913),
 'rooms_media': np.float64(3.0063856960408684),
 'rooms_varianza': np.float64(0.7045627513040866),
 'surface_media': np.float64(111.75222363405337),
 'surface_varianza': np.float64(4263.051760316336),
 'bathrooms_media': np.float64(1.6363636363636365),
 'bathrooms_varianza': np.float64(0.5727272727272728)}

#### Ejercicio 15

¿Cuál es la casa más cara de cada población del cinturón sur de Madríd? (★★☆)

> Debes usar el subset obtenido en la pregunta 13

- Genera un DataFrame con esta información
- Muestra tanto la dirección como el precio de la casa seleccionada de cada población.
- Genera conclusiones en una celda markdown

In [23]:
indices_mas_caras = df_sur.groupby('level5')['price'].idxmax()

df_mas_caras = df_sur.loc[indices_mas_caras, ['level5', 'address', 'price']]

df_mas_caras

            level5                                address    price
5585      Alcorcón                               Alcorcón   950000
11561  Fuenlabrada  Calle de Paulo Freire, 5, Fuenlabrada   490000
2881        Getafe                                 Getafe  1050000
10412      Leganés           Avenida Reina Sofía, Leganés   650000

### Conclusiones

Al obtener la casa más cara de cada municipio del cinturón sur, se observa que los precios máximos son muy diferentes entre sí, lo que muestra que cada población ofrece tipos de propiedades muy distintas, siendo Getafe la población que registra la casa con el precio más elevado de toda la zona sur.

#### Ejercicio 16

¿Qué puedes decir acerca del precio por metro cuadrado (precio/m2) entre los municipios de 'Getafe' y 'Alcorcón'? (★★☆)

> Debes usar el subset obtenido en la pregunta 13
>
> Pista: Crea una nueva columna llamada `pps` (price per square en inglés) y luego analiza los valores

In [24]:
df_sur['pps'] = df_sur['price'] / df_sur['surface']

pps_getafe = df_sur[df_sur['level5'] == 'Getafe']['pps'].mean()
pps_alcorcon = df_sur[df_sur['level5'] == 'Alcorcón']['pps'].mean()

print(f"Precio promedio por m² en Getafe: {pps_getafe:.2f} €/m²")
print(f"Precio promedio por m² en Alcorcón: {pps_alcorcon:.2f} €/m²")

Precio promedio por m² en Getafe: 2066.31 €/m²
Precio promedio por m² en Alcorcón: 2239.30 €/m²

#### Ejercicio 17

Escribe aquí tus conclusiones acerca de este proyecto

Desde el punto de vista técnico, el análisis permitió transformar miles de publicaciones inmobiliarias en información clave para entender el mercado. Al limpiar la base de datos y conservar más de 14.000 propiedades representativas, el estudio identificó los techos y pisos de precios del sector, así como las viviendas con superficies extremas.

El uso del precio por metro cuadrado resultó fundamental para neutralizar las diferencias de tamaño entre propiedades y comparar objetivamente distintos municipios. Además, el análisis del cinturón sur de Madrid mostró una amplia variedad en la oferta de cada localidad. En conclusión, los datos procesados demuestran que el valor de un inmueble está fuertemente determinado por su localización y el tipo de producto, más allá de su tamaño.

Personalmente, me sirvió bastante aplicar los conceptos trabajados en función de un mismo ejercicio para bajarlos aún más a tierra y encontrar cierta continuidad en el proceso.